# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 405, 1080))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(44, 48, 57);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(46, 261, 313, 67))
        self.frame_2.setStyleSheet("font: 75 26pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.lbl_profile = QtWidgets.QLabel(self.frame_2)
        self.lbl_profile.setGeometry(QtCore.QRect(0, 0, 313, 67))
        self.lbl_profile.setStyleSheet("QLabel {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(12, 140, 233);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}")
        self.lbl_profile.setObjectName("lbl_profile")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(46, 352, 313, 304))
        self.frame_3.setStyleSheet("font: 75 26pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.lbl_edu = QtWidgets.QLabel(self.frame_3)
        self.lbl_edu.setGeometry(QtCore.QRect(0, 0, 313, 67))
        self.lbl_edu.setStyleSheet("font: 75 26pt \"Open Sans\";\n"
"color: rgb(158, 172, 183);\n"
"text-align: left;\n"
"margin-left: 32;")
        self.lbl_edu.setObjectName("lbl_edu")
        self.lbl_theory = QtWidgets.QLabel(self.frame_3)
        self.lbl_theory.setGeometry(QtCore.QRect(0, 67, 313, 67))
        self.lbl_theory.setStyleSheet("QLabel {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: left;\n"
"    margin-left: 52;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(12, 140, 233);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}")
        self.lbl_theory.setObjectName("lbl_theory")
        self.lbl_tasks = QtWidgets.QLabel(self.frame_3)
        self.lbl_tasks.setGeometry(QtCore.QRect(0, 134, 313, 67))
        self.lbl_tasks.setStyleSheet("QLabel {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: left;\n"
"    margin-left: 52;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(12, 140, 233);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}")
        self.lbl_tasks.setObjectName("lbl_tasks")
        self.lbl_testing = QtWidgets.QLabel(self.frame_3)
        self.lbl_testing.setGeometry(QtCore.QRect(0, 201, 313, 67))
        self.lbl_testing.setStyleSheet("QLabel {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: left;\n"
"    margin-left: 52;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(12, 140, 233);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}")
        self.lbl_testing.setObjectName("lbl_testing")
        self.lbl_arrow = QtWidgets.QLabel(self.frame_3)
        self.lbl_arrow.setGeometry(QtCore.QRect(253, 33, 22, 11))
        self.lbl_arrow.setText("")
        self.lbl_arrow.setPixmap(QtGui.QPixmap("../../Проектирование интерфейса/Arrow.svg"))
        self.lbl_arrow.setObjectName("lbl_arrow")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(46, 656, 313, 67))
        self.frame_4.setStyleSheet("font: 75 26pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.lbl_graph_emb = QtWidgets.QLabel(self.frame_4)
        self.lbl_graph_emb.setGeometry(QtCore.QRect(0, 0, 313, 67))
        self.lbl_graph_emb.setStyleSheet("QLabel {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    font: 75 26pt \"Open Sans\";\n"
"    color: rgb(12, 140, 233);\n"
"    text-align: left;\n"
"    margin-left: 32;\n"
"}")
        self.lbl_graph_emb.setObjectName("lbl_graph_emb")
        self.lbl_logo = QtWidgets.QLabel(self.frame)
        self.lbl_logo.setGeometry(QtCore.QRect(108, 48, 189, 117))
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("../../Проектирование интерфейса/logo_white.svg"))
        self.lbl_logo.setScaledContents(False)
        self.lbl_logo.setObjectName("lbl_logo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PlanarEd"))
        self.lbl_profile.setText(_translate("MainWindow", "Профиль"))
        self.lbl_edu.setText(_translate("MainWindow", "Обучение"))
        self.lbl_theory.setText(_translate("MainWindow", "Теория"))
        self.lbl_tasks.setText(_translate("MainWindow", "Задания"))
        self.lbl_testing.setText(_translate("MainWindow", "Тестирование"))
        self.lbl_graph_emb.setText(_translate("MainWindow", "Укладка графа"))
