# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_graph_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphPage(object):
    def setupUi(self, GraphPage):
        GraphPage.setObjectName("GraphPage")
        GraphPage.resize(410, 374)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GraphPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_file = QtWidgets.QPushButton(GraphPage)
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout_2.addWidget(self.btn_file)
        self.lbl_file_name = QtWidgets.QLabel(GraphPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_file_name.sizePolicy().hasHeightForWidth())
        self.lbl_file_name.setSizePolicy(sizePolicy)
        self.lbl_file_name.setObjectName("lbl_file_name")
        self.horizontalLayout_2.addWidget(self.lbl_file_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lbl_graph_info = QtWidgets.QLabel(GraphPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_graph_info.sizePolicy().hasHeightForWidth())
        self.lbl_graph_info.setSizePolicy(sizePolicy)
        self.lbl_graph_info.setText("")
        self.lbl_graph_info.setObjectName("lbl_graph_info")
        self.verticalLayout.addWidget(self.lbl_graph_info)
        self.btn_draw = QtWidgets.QPushButton(GraphPage)
        self.btn_draw.setObjectName("btn_draw")
        self.verticalLayout.addWidget(self.btn_draw)
        self.lbl_algorithm = QtWidgets.QLabel(GraphPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_algorithm.sizePolicy().hasHeightForWidth())
        self.lbl_algorithm.setSizePolicy(sizePolicy)
        self.lbl_algorithm.setObjectName("lbl_algorithm")
        self.verticalLayout.addWidget(self.lbl_algorithm)
        self.cbx_algorithm = QtWidgets.QComboBox(GraphPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_algorithm.sizePolicy().hasHeightForWidth())
        self.cbx_algorithm.setSizePolicy(sizePolicy)
        self.cbx_algorithm.setObjectName("cbx_algorithm")
        self.cbx_algorithm.addItem("")
        self.cbx_algorithm.addItem("")
        self.cbx_algorithm.addItem("")
        self.verticalLayout.addWidget(self.cbx_algorithm)
        self.btn_embed = QtWidgets.QPushButton(GraphPage)
        self.btn_embed.setObjectName("btn_embed")
        self.verticalLayout.addWidget(self.btn_embed)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(GraphPage)
        self.cbx_algorithm.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GraphPage)

    def retranslateUi(self, GraphPage):
        _translate = QtCore.QCoreApplication.translate
        GraphPage.setWindowTitle(_translate("GraphPage", "Form"))
        self.btn_file.setText(_translate("GraphPage", "Выбрать файл"))
        self.lbl_file_name.setText(_translate("GraphPage", "Имя файла"))
        self.btn_draw.setText(_translate("GraphPage", "Нарисовать граф"))
        self.lbl_algorithm.setText(_translate("GraphPage", "Выберите алгоритм:"))
        self.cbx_algorithm.setItemText(0, _translate("GraphPage", "Гамма-алгоритм"))
        self.cbx_algorithm.setItemText(1, _translate("GraphPage", "Алгоритм, основанный на методе отжига"))
        self.cbx_algorithm.setItemText(2, _translate("GraphPage", "Алгоритм на PQ-деревьях"))
        self.btn_embed.setText(_translate("GraphPage", "Уложить граф"))
