# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilePage(object):
    def setupUi(self, ProfilePage):
        ProfilePage.setObjectName("ProfilePage")
        ProfilePage.resize(415, 285)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProfilePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_fixed_surname = QtWidgets.QLabel(ProfilePage)
        self.lbl_fixed_surname.setObjectName("lbl_fixed_surname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_fixed_surname)
        self.lbl_fixed_name = QtWidgets.QLabel(ProfilePage)
        self.lbl_fixed_name.setObjectName("lbl_fixed_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_fixed_name)
        self.lbl_fixed_midname = QtWidgets.QLabel(ProfilePage)
        self.lbl_fixed_midname.setObjectName("lbl_fixed_midname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_fixed_midname)
        self.lbl_fixed_group = QtWidgets.QLabel(ProfilePage)
        self.lbl_fixed_group.setObjectName("lbl_fixed_group")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_fixed_group)
        self.lbl_surname = QtWidgets.QLabel(ProfilePage)
        self.lbl_surname.setObjectName("lbl_surname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_surname)
        self.lbl_name = QtWidgets.QLabel(ProfilePage)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_name)
        self.lbl_midname = QtWidgets.QLabel(ProfilePage)
        self.lbl_midname.setObjectName("lbl_midname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_midname)
        self.lbl_group = QtWidgets.QLabel(ProfilePage)
        self.lbl_group.setObjectName("lbl_group")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_group)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(ProfilePage)
        QtCore.QMetaObject.connectSlotsByName(ProfilePage)

    def retranslateUi(self, ProfilePage):
        _translate = QtCore.QCoreApplication.translate
        ProfilePage.setWindowTitle(_translate("ProfilePage", "Form"))
        self.lbl_fixed_surname.setText(_translate("ProfilePage", "Фамилия:"))
        self.lbl_fixed_name.setText(_translate("ProfilePage", "Имя:"))
        self.lbl_fixed_midname.setText(_translate("ProfilePage", "Отчество:"))
        self.lbl_fixed_group.setText(_translate("ProfilePage", "Группа:"))
        self.lbl_surname.setText(_translate("ProfilePage", "TextLabel"))
        self.lbl_name.setText(_translate("ProfilePage", "TextLabel"))
        self.lbl_midname.setText(_translate("ProfilePage", "TextLabel"))
        self.lbl_group.setText(_translate("ProfilePage", "TextLabel"))
