# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilePage(object):
    def setupUi(self, ProfilePage):
        ProfilePage.setObjectName("ProfilePage")
        ProfilePage.resize(415, 285)
        self.lbl_name = QtWidgets.QLabel(ProfilePage)
        self.lbl_name.setGeometry(QtCore.QRect(50, 100, 301, 16))
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_surname = QtWidgets.QLabel(ProfilePage)
        self.lbl_surname.setGeometry(QtCore.QRect(50, 80, 301, 16))
        self.lbl_surname.setObjectName("lbl_surname")
        self.lbl_midname = QtWidgets.QLabel(ProfilePage)
        self.lbl_midname.setGeometry(QtCore.QRect(50, 120, 301, 16))
        self.lbl_midname.setObjectName("lbl_midname")
        self.lbl_group = QtWidgets.QLabel(ProfilePage)
        self.lbl_group.setGeometry(QtCore.QRect(50, 160, 301, 16))
        self.lbl_group.setObjectName("lbl_group")

        self.retranslateUi(ProfilePage)
        QtCore.QMetaObject.connectSlotsByName(ProfilePage)

    def retranslateUi(self, ProfilePage):
        _translate = QtCore.QCoreApplication.translate
        ProfilePage.setWindowTitle(_translate("ProfilePage", "Form"))
        self.lbl_name.setText(_translate("ProfilePage", "Имя:"))
        self.lbl_surname.setText(_translate("ProfilePage", "Фамилия:"))
        self.lbl_midname.setText(_translate("ProfilePage", "Отчество"))
        self.lbl_group.setText(_translate("ProfilePage", "Группа:"))
