# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_theory_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TheoryPage(object):
    def setupUi(self, TheoryPage):
        TheoryPage.setObjectName("TheoryPage")
        TheoryPage.resize(685, 590)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TheoryPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_theme_1 = QtWidgets.QLabel(TheoryPage)
        self.lbl_theme_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_theme_1.setObjectName("lbl_theme_1")
        self.verticalLayout.addWidget(self.lbl_theme_1)
        self.lbl_theme_2 = QtWidgets.QLabel(TheoryPage)
        self.lbl_theme_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_theme_2.setObjectName("lbl_theme_2")
        self.verticalLayout.addWidget(self.lbl_theme_2)
        self.lbl_theme_3 = QtWidgets.QLabel(TheoryPage)
        self.lbl_theme_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_theme_3.setObjectName("lbl_theme_3")
        self.verticalLayout.addWidget(self.lbl_theme_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(TheoryPage)
        QtCore.QMetaObject.connectSlotsByName(TheoryPage)

    def retranslateUi(self, TheoryPage):
        _translate = QtCore.QCoreApplication.translate
        TheoryPage.setWindowTitle(_translate("TheoryPage", "Form"))
        self.lbl_theme_1.setText(_translate("TheoryPage", "Тема 1"))
        self.lbl_theme_2.setText(_translate("TheoryPage", "Тема 2"))
        self.lbl_theme_3.setText(_translate("TheoryPage", "Тема 3"))
